services:
  freshrss-db:
    image: mariadb:lts
    container_name: freshrss-db
    command: "'mariadbd' '--character-set-server=utf8mb4' '--collation-server=utf8mb4_bin'"
    user: ${PUID}:${PGID}
    env_file:
      - sops-secrets.env
    ports:
      - 3308:3306
    volumes:
      - ${DB_DATA_LOCATION}/db-mdb:/var/lib/mysql
    labels:
      - "autoheal=true"
      - "com.centurylinklabs.watchtower.scope=true"
    restart: unless-stopped
