services:
  dockhand:
    image: fnsys/dockhand:latest
    container_name: dockhand
    environment:
      DATABASE_URL: postgres://${DB_USERNAME}:${DB_PASSWORD}@db:5432/${DB_DATABASE}
    ports:
      - 3000:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/corey/docker/dockhand/config:/app/data
    labels:
      - "autoheal=true"
      - "com.centurylinklabs.watchtower.scope=true"
    depends_on:
      - db
    restart: unless-stopped
  
  db:
    image: postgres:16-alpine
    container_name: dockhand-db
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - /home/corey/docker/dockhand/db:/var/lib/postgresql/data
    labels:
      - "autoheal=true"
      - "com.centurylinklabs.watchtower.scope=true"
    restart: unless-stopped