services:
  autoheal:
    image: willfarrell/autoheal:latest
    container_name: util-autoheal
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    environment:
      - TZ=America/New_York
      - AUTOHEAL_CONTAINER_LABEL=all
      - AUTOHEAL_DEFAULT_STOP_TIMEOUT=10
      - AUTOHEAL_INTERVAL=5
      - AUTOHEAL_START_PERIOD=0
      - CURL_TIMEOUT=30
    labels:
      - "com.centurylinklabs.watchtower.scope=true"
    restart: unless-stopped

  watchtower:
    image: nickfedor/watchtower:latest
    container_name: util-watchtower
    environment:
      - TZ=America/New_York
      - WATCHTOWER_CLEANUP=true
      - "WATCHTOWER_SCHEDULE=0 0 1 * * *"
      - WATCHTOWER_SCOPE=true
      - WATCHTOWER_TIMEOUT=30s
      #- WATCHTOWER_LABEL_ENABLE=true
    labels:
      - "autoheal=true"
      - "com.centurylinklabs.watchtower.scope=true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  dockerproxy:
    image: ghcr.io/tecnativa/docker-socket-proxy:latest
    container_name: util-docker-socket-proxy
    environment:
      - CONTAINERS=1 # Allow access to viewing containers
      - SERVICES=1 # Allow access to viewing services (necessary when using Docker Swarm)
      - TASKS=1 # Allow access to viewing tasks (necessary when using Docker Swarm)
      - POST=0 # Disallow any POST operations (effectively read-only)
    labels:
      - "autoheal=true"
      - "com.centurylinklabs.watchtower.scope=true"
    ports:
      - 2375:2375
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # Mounted as read-only
    restart: unless-stopped

  portainer:
    image: portainer/agent:latest
    container_name: util-portainer
    ports:
      - 9001:9001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "autoheal=true"
      - "com.centurylinklabs.watchtower.scope=true"
    restart: always
