services:
  db-backup:
    image: tiredofit/db-backup:latest
    container_name: admin-backup
    volumes:
      - /volume1/snapshots/databases:/backup
      - /volume1/databases/admin-backup/logs:/logs
    dns:
      - 10.69.1.2
      - 10.69.1.3
    labels:
      - "autoheal=true"
      - "com.centurylinklabs.watchtower.scope=true"
    restart: unless-stopped
    environment:
      # Setup
      - CONTAINER_ENABLE_MONITORING=FALSE
      - USER_DBBACKUP=1038
      - GROUP_DBBACKUP=100
      - TIMEZONE=America/New_York
      - BACKUP_JOB_CONCURRENCY=1
      - DEFAULT_CHECKSUM=SHA1
      - DEFAULT_COMPRESSION=GZ
      - DEFAULT_BACKUP_INTERVAL=1440
      - DEFAULT_BACKUP_BEGIN=1205
      - DEFAULT_CLEANUP_TIME=8640

      # FreshRSS
      - DB01_TYPE=mariadb
      - DB01_HOST=10.69.1.40
      - DB01_PORT=3308
      - DB01_NAME=freshrss
      - DB01_USER=freshrss
      - DB01_PASS=${DB_PASS_FRESHRSS}
      
      # Joplin
      - DB02_TYPE=postgres
      - DB02_HOST=10.69.1.40
      - DB02_PORT=5433
      - DB02_NAME=joplin
      - DB02_USER=joplin
      - DB02_PASS=${DB_PASS_JOPLIN}
      - DB02_AUTH=joplin
      
      # YouTube-DL
      - DB03_TYPE=mongo
      - DB03_HOST=10.69.1.40
      - DB03_PORT=27017
      
      # Immich
      - DB04_TYPE=postgres
      - DB04_HOST=10.69.1.40
      - DB04_PORT=5434
      - DB04_NAME=immich
      - DB04_USER=postgres
      - DB04_PASS=${DB_PASS_IMMICH}
      - DB04_AUTH=immich

      # Speedtest-Tracker
      - DB05_TYPE=postgres
      - DB05_HOST=10.69.1.40
      - DB05_PORT=5435
      - DB05_NAME=speedtest_tracker
      - DB05_USER=speedy
      - DB05_PASS=${DB_PASS_SPEEDTEST}
      - DB05_AUTH=speedtest_tracker
      
      # Traccar
      - DB06_TYPE=mariadb
      - DB06_HOST=10.69.1.40
      - DB06_PORT=3309
      - DB06_NAME=traccar
      - DB06_USER=traccar
      - DB06_PASS=${DB_PASS_TRACCAR}

      # LubeLogger
      - DB07_TYPE=postgres
      - DB07_HOST=10.69.1.40
      - DB07_PORT=5437
      - DB07_NAME=lubelogger
      - DB07_USER=lubelogger
      - DB07_PASS=${DB_PASS_LUBELOGGER}
      - DB07_AUTH=lubelogger

      # cnpg-cluster
      - DB08_TYPE=pgsql
      - DB08_HOST=cnpg.local.cvsickle.com
      - DB08_PORT=5432
      - DB08_NAME=ALL
      - DB08_SPLIT=TRUE
      - DB08_USER=corey
      - DB08_PASS=${DB_PASS_CNPG}
      - DB08_AUTH=postgres
      - DB08_SKIP_AVAILABILITY_CHECK=true
      - DB08_LOG_LEVEL=DEBUG
      
      # mariadb-cluster
      - DB09_TYPE=mariadb
      - DB09_HOST=mdb.local.cvsickle.com
      - DB09_PORT=3306
      - DB09_NAME=ALL
      - DB09_SPLIT=TRUE
      - DB09_USER=corey
      - DB09_PASS=${DB_PASS_MARIADB_CLUSTER}
