services:
  filebrowser:
    image: filebrowser/filebrowser:v2-s6
    container_name: filebrowser
    #user: "1000:10000"
    environment:
      - PUID=1000
      - PGID=10000
    ports:
      - 8001:80
    volumes:
      - /home/corey/docker/filebrowser/database:/database
      - /home/corey/docker/filebrowser/config:/config
      - /mnt/files:/srv
    labels:
      - "autoheal=true"
      - "com.centurylinklabs.watchtower.scope=true"
    restart: unless-stopped