services:
  maintenance-page:
    image: csana/maintenance:latest
    container_name: maintenance-page
    ports:
      - 8010:80
    volumes:
      - ${DIR_CONFIG}/maintenance/page.html:/usr/share/nginx/html/index.html
    labels:
      - "autoheal=true"
      - "com.centurylinklabs.watchtower.scope=true"
    restart: unless-stopped
